- name: install docker worker 1
  hosts: swarm_worker
  become: true
  roles:
  - install_docker

- name: install docker on worker 2
  hosts: swarm_worker_2
  become: true
  roles:
  - install_docker

- name: install docker on localhost
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
  - install_docker

- name: initialise docker swarm on master node
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
  - docker_init

- name: add worker to swarm
  hosts: swarm_worker
  become: true
  roles:
  - add_swarm

- name: add worker to swarm
  hosts: swarm_worker_2
  become: true
  roles:
  - add_swarm